version: '3.9'
services:
  redis:
    image: redis:6.2.6
    ports:
      - 6380:6379
    restart: always
    container_name: redis
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/redis.conf
    command: ['redis-server', '/redis.conf']
    networks:
      - kurakichi-dev
  postgres:
    image: postgres:14.2
    ports:
      - 5432:5432
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./postgres:/var/lib/postgresql/data
      # - ./postgres/logs:/var/log
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - kurakichi-dev

networks:
  kurakichi-dev:
