import { FC } from 'react';
import { Article } from '../molecules';

// type ArticlesWelfareGuideProps = {};
type TempListProps = {
  contents: string[];
};

const TempList: FC<TempListProps> = ({ contents }) => (
  <ul className="flex flex-col items-start ml-3 list-disc list-inside">
    {contents.map((content) => (
      <li key={content}>{content}</li>
    ))}
  </ul>
);
export const ArticlesWelfareGuide: FC = () => (
  <div className="grid grid-cols-1 gap-8 mt-10 md:grid-cols-2 xl:grid-cols-3">
    <Article
      imageSrc="/save_money_pig.jpg"
      title="暮らし"
      description={
        <TempList
          contents={[
            '生活費が足りない',
            '住む場所がない',
            '働くことが出来ない',
            '出産・入学・入退院などで生活が苦しい',
            '結婚資金が足りない',
            '生活福祉資金貸付制度を利用する',
          ]}
        />
      }
      linkUrl="/knowledge/life"
    />
    <Article
      imageSrc="/worker.webp"
      title="仕事"
      description={
        <TempList
          contents={[
            '就職のための訓練を受けたい',
            '仕事のスキルアップをしたい',
            '日雇い雇用の仕事がない',
            '仕事で怪我・病気になった',
            '仕事で家族が亡くなった',
            '失業・怪我・育児による休業をした',
          ]}
        />
      }
      linkUrl="/knowledge/work"
    />
    <Article
      imageSrc="/patient.jpg"
      title="医療・障害"
      description={
        <TempList
          contents={[
            '健康保険料が支払えない',
            '医療費が高すぎる',
            '重い病気になった',
            '障碍になった(視聴覚・言語・臓器など)',
            '家族が知的障害だ',
            '医療に関わる税金の控除を受けたい',
            '発達障害・高次脳機能障害かもしれない',
          ]}
        />
      }
      linkUrl="/knowledge/medical"
    />
    <Article
      imageSrc="/pregnant.jpg"
      title="妊娠・出産"
      description={
        <TempList
          contents={[
            '妊婦健診の費用補助',
            '出産費用の支援',
            '不妊治療費助成制度',
            '産休に係る社会保険免除',
            '出産費貸付制度',
          ]}
        />
      }
      linkUrl="/knowledge/child"
    />
    <Article
      imageSrc="/father_and_girl.jpg"
      title="育児"
      description={
        <TempList
          contents={[
            '育児休業給付金を受ける',
            'ひとり親職業訓練給付金',
            '毎月の児童手当',
          ]}
        />
      }
      linkUrl="/knowledge/child"
    />
    <Article
      imageSrc="/nursing-elder.jpg"
      title="介護"
      description={
        <TempList
          contents={[
            '介護保険が支払えない',
            '介護サービス費が高すぎる',
            '介護によって休業した',
            '介護の支援を受けたい',
          ]}
        />
      }
      linkUrl="/knowledge/medical"
    />
    <Article
      imageSrc="/pension.jpg"
      title="年金"
      description={
        <TempList
          contents={[
            '国民年金を支払えない',
            '遺族年金を受け取る',
            '年金だけで暮らしていけない',
            '亡くなった家族の年金を受け取る',
          ]}
        />
      }
      linkUrl="/knowledge/pension"
    />
    <Article
      imageSrc="/house.jpg"
      title="住居"
      description={
        <TempList
          contents={[
            '住宅ローン減税を利用する',
            '省エネ改修のための補助金',
            '減税を利用する',
            'バリアフリーのための減税制度を利用する',
          ]}
        />
      }
      linkUrl="/knowledge/house"
    />
    <Article
      imageSrc="/lawyer.jpg"
      title="法律"
      description={
        <TempList contents={['弁護士を雇いたい', '相談したいがお金がない']} />
      }
      linkUrl="/knowledge/law"
    />
  </div>
);
